language: node_js

node_js:
  - "6"
  - "8"

install:
  - npm install

script:
  - npm run eslint
  - npm run test

notifications:
  email:
    recipients:
      - bob76828@gmail.com
      - lalayueh@gmail.com
      - dy93_@hotmail.com
      - drumrick.1600@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
